### PR TITLE
Add Github Actions for all platforms (WIP)

### PR DESCRIPTION
**Pull request by 2shady4u**
@piiertho @CedNaru This PR adds Github Actions for all supported platforms.

Capture

- Linux
- Windows
- MacOS
- Android (armv7, arm64v8)
- iOS (arm64)

Mayhaps not all those android nor ios platforms should be supported as they make the CI of those platforms rather long (~ 10 minutes). Please give feedback.

This also replaces the `getFmod2.sh`-script with a python script (`get_fmod.py`) which has better readability and works fully cross-platform. (It was pretty much impossible to get the shell-script to run on a native windows machine...) I still need to clean up that script a bit though!

I also had to do some edits in the `Android.mk`-file, namely changing the paths of the cloned godot-cpp repository and the location of the extracted fmod header files.

There are still some things that will need to be fixed/added:
- [x] Fix folder structure and reset `Android.mk` to its original state.
- [x] Adding the compiled godot-cpp bindings to the ios bin/-folder (since this is required due to ios having static libraries)
- [x] Trigger on Pull Requests
- [x] Release jobs triggered on tags
- [x] Actually testing all the libraries (???)
- [x] Also running GUT so the CI/CD can be used for checking PRs (???)

Cheers!

### CODE REVIEW

**Comment by JezSonic** [comment]
Why not Android x86_64?
In Application.mk you can just set the target arch property to `all` so this will compile code for all supported platforms

**Comment by JezSonic** [comment]
Actually if you need to compile godot-cpp for android x86_64 and it is not supported arch by default i can share you my modified SConstruct file to make compilation for this architecture possible

**Comment by piiertho** [comment]
I would give up armv7. This makes ios binaries really big.  
x86_64 can be usefull, but it is not supported officially in godot-cpp bindings.  
@JezSonic we already used a modified SConstruct here: https://github.com/utopia-rise/godot-cpp to get proper android and ios support.  
I think that now ios support is better in official repo. But for android there are some missing env variables, see here: https://github.com/godotengine/godot-cpp/issues/488

**Comment by piiertho** [comment]
@2shady4u I would also add release jobs on tags to the check list, if it's ok to you.

**Comment by CedNaru** [comment]
Good job. 
And yeah, we don't aim for supporting all platforms and CPUs. That's why we don't support 32 bits and Android x86, it's certainly possible to compile for them with a few changes but we don't want to support dying platforms in the long term.

**Comment by 2shady4u** [comment]
Okay, I switched the `godot-cpp/` and `libs/fmod/` paths to be outside the project folder as requested by @piiertho 
I also added the compiled godot-cpp bindings file for ios to the uploaded artefact as this is required.

Also cleaned up all other artefacts so unneeded files aren't added anymore.

@CedNaru @piiertho Should this also trigger on pull requests?

**Comment by 2shady4u** [comment]
Ok, I had to do some modifications to get everything working properly.
Now there's only one workflow file `all_builds.yml` that triggers all the builds and the release (on tag).
actions

Pushing a tag to origin automatically creates a release and adds the compiled artifacts to this release, here's an example:
https://github.com/2shady4u/fmod-gdnative/releases/tag/v9000
release

Evidently you'll still have to edit the release title and body manually, but that's to be expected.

Also the Github Actions triggers on Pull Requests as shown here:
https://github.com/2shady4u/fmod-gdnative/pull/1
PR

I don't think I'll add automatic GUT atm, because it will probably bloat the compilation of the Github Actions too much. Also I do think Github Actions fully replaces all functionalities that travis had previously.

What do you think? @CedNaru @piiertho

**Comment by 2shady4u** [comment]
Seems that the GUT testing is an actual necessary feature so I'll see what I can do 🤔 

However, I do require more information regarding the actually requires features that should still be implemented.

Currently, I'm out of time to work on this, but I'll get back to it... once I have the necessary information of the specs.

**Comment by JezSonic** [comment]
you know. i have reviewed code and i have some time, i can help you with testing android builds and adding x86_64
also what about 32bit pc platforms?

**Review by JezSonic — COMMENTED** [review]
Looks like there are no issues, i'll download it later and add support for all android libs (need this for myself, also I think other people will like this), but i dont wan to approve this for now. i prefer the repo owner to do that

**Comment by 2shady4u** [comment]
image

GUT testing is now implemented 🥳

**Comment by 2shady4u** [comment]
@CedNaru and @piiertho , I think I'm finally done 🥳 

**So a brief summary of the features:**

- Github actions runs on PR and checks all platforms and a GUT test, as seen here:
image

https://github.com/2shady4u/fmod-gdnative/pull/4

- A new release is automatically created whenever a tag is pushed, as seen here:
image

https://github.com/2shady4u/fmod-gdnative/releases/tag/vtest

No fmod or fmodstudio are present!!!
To correct set this up you'll have to do the following:
- Add following secrets to this repository:
image

FMODUSER = your fmod user-account/name
FMODPASS = your fmod password

- Remove the test branches from the YML so only the master branch remains:
image

(should be: `branches : [ master ]` at line 4)

That should hopefully be it?

**Review by piiertho — APPROVED** [review]
Thx a lot for the contribution !

**Pull request merged**
