### PR TITLE
Test CI from fork

### PR DESCRIPTION
**Pull request by 2shady4u**
Test to see if I can trigger CI with secrets from my fork

### CODE REVIEW

**Comment by bitbrain** [comment]
Reading this thread https://github.community/t/make-secrets-available-to-builds-of-forks/16166/34 other people seem to have trouble doing the same. Do we have any example on this project where someone raised a PR from a fork and it was built successfully?

**Comment by bitbrain** [comment]
Ah yes, this one https://github.com/utopia-rise/fmod-gdnative/pull/77

**Comment by 2shady4u** [comment]
> 
> 
> Ah yes, this one #77

Yeah, but that's because we were still using `pull_request_target` at that time.
Recently we switched to `pull_request` in `all_builds.yml` (https://github.com/utopia-rise/fmod-gdnative/pull/89) and after that builds don't succeed any longer.
This change was done such that PR are correctly tested.
Before that the CI of a PR ran on the latest master commit and NOT on the PR's commit which destroyed the entire purpose of having CI in a PR at all 🤷 

We'll probably need to implement something like this to fix this issue:
https://github.com/imjohnbo/ok-to-test

**Comment by bitbrain** [comment]
I am wondering: couldn't we do some trickery by creating a branch off `master` with the same name as the fork branch, then merging the changes from the fork branch into this repository and then simply run the build/test on that branch (which belongs to this repo) so it can use the secrets from this repo, not from the forks? We would just need to ensure that branches are cleaned up properly after merging, also conflicting remote branch names from different forks might cause weirdness.

**Comment by bitbrain** [comment]
I created https://github.com/utopia-rise/fmod-gdnative/issues/95 to track this issue.

**Pull request closed without merging**
